### ISSUE TITLE
internal link to Scout24 Data Landscape Manifesto 

### ISSUE THREAD

**Issue by eschumann** [Scout24/scout24-engineering-values-and-principles#3]
https://github.com/Scout24/scout24-engineering-values-and-principles/blob/master/2-engineering-principles.md#data-is-a-shared-asset contains a link to
The Scout24 Data Landscape Manifesto at https://medium.com/@seangustafson/f9816ea10af8

It would be great to reference a company-internal version/copy/original instead of an article at medium.com. Additionally Medium requires login (from time to time).

**Comment by sgeb** [comment]
Hi @eschumann, thanks for your input.

The engineering values and principles are meant to be internet-public. Therefore we intentionally linked to a public page for the Scout24 Data Landscape Manifesto. Previously it was a link to a protected page, accessible only company-internally.

Now, use of medium.com is arguable. It's the channel the Data Team has chosen for their publication. We're happy to change the link if a more suitable internet-public one exists.

**Comment by sgeb** [comment]
I'll close this issue for now. Please re-open for further discussion and/or suggest a different link we could use. Thanks!
